// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingManagment.Repository.Data;

namespace TrainingManagment.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230911114721_AddNewColumnsToUsersTable")]
    partial class AddNewColumnsToUsersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Security");
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LookupCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyOn");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LookupCategoryId");

                    b.ToTable("Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(1796),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 100,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "عمل",
                            NameEn = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3392),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 100,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "جامعة",
                            NameEn = "University"
                        },
                        new
                        {
                            Id = 3,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3408),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = ".Net",
                            NameEn = "DotNet"
                        },
                        new
                        {
                            Id = 4,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3414),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "محلل أعمال",
                            NameEn = "BusinessAnalyst"
                        },
                        new
                        {
                            Id = 5,
                            Code = 3,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3417),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "مراقبة الجودة",
                            NameEn = "QualityControl"
                        },
                        new
                        {
                            Id = 6,
                            Code = 4,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3419),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "بنية الأنظمة",
                            NameEn = "Infrastructure"
                        },
                        new
                        {
                            Id = 7,
                            Code = 5,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3422),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "واجهة المستخدم وتجربة المستخدم",
                            NameEn = "UI_UX"
                        },
                        new
                        {
                            Id = 8,
                            Code = 6,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3424),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "الموارد البشرية",
                            NameEn = "HumanResources"
                        },
                        new
                        {
                            Id = 9,
                            Code = 7,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3427),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "المالية",
                            NameEn = "Finance"
                        },
                        new
                        {
                            Id = 10,
                            Code = 8,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3430),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 200,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "الذكاء الاصطناعي",
                            NameEn = "AI"
                        },
                        new
                        {
                            Id = 11,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3433),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 300,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "نشط",
                            NameEn = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3435),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 300,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "قيد الانتظار",
                            NameEn = "Pending"
                        },
                        new
                        {
                            Id = 13,
                            Code = 3,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3438),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 300,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "مكتمل",
                            NameEn = "Finished"
                        },
                        new
                        {
                            Id = 14,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3442),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 400,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "الانضمام إلى فريق TPS",
                            NameEn = "Joining_TPS_Team"
                        },
                        new
                        {
                            Id = 15,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3444),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 400,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "معلق",
                            NameEn = "On_Hold"
                        },
                        new
                        {
                            Id = 16,
                            Code = 3,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3448),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 400,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "مرفوض",
                            NameEn = "Rejected"
                        },
                        new
                        {
                            Id = 17,
                            Code = 4,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3451),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 400,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "استقال",
                            NameEn = "Quit"
                        },
                        new
                        {
                            Id = 18,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3453),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "خالد سلامة",
                            NameEn = "Khalid_Salameh"
                        },
                        new
                        {
                            Id = 19,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3456),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "لميس حوراني",
                            NameEn = "Lamees_Hourani"
                        },
                        new
                        {
                            Id = 20,
                            Code = 3,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3459),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "مريم السعداوي",
                            NameEn = "Mariam_AlSadawi"
                        },
                        new
                        {
                            Id = 21,
                            Code = 4,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3461),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "محمد حماد",
                            NameEn = "Mohammad_Hamad"
                        },
                        new
                        {
                            Id = 22,
                            Code = 5,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3464),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "محمد عبده",
                            NameEn = "Mohammad_Ibdah"
                        },
                        new
                        {
                            Id = 23,
                            Code = 6,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3467),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "صفاء",
                            NameEn = "Safaa"
                        },
                        new
                        {
                            Id = 24,
                            Code = 7,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3469),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "زكريا لافي",
                            NameEn = "Zakaria_Lafi"
                        },
                        new
                        {
                            Id = 25,
                            Code = 8,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3472),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 500,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "أحمد سويلم",
                            NameEn = "Ahmed_Sweilem"
                        },
                        new
                        {
                            Id = 26,
                            Code = 2023,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3474),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2023",
                            NameEn = "Year2023"
                        },
                        new
                        {
                            Id = 27,
                            Code = 2024,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3477),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2024",
                            NameEn = "Year2024"
                        },
                        new
                        {
                            Id = 28,
                            Code = 2025,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3480),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2025",
                            NameEn = "Year2025"
                        },
                        new
                        {
                            Id = 29,
                            Code = 2026,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3482),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2026",
                            NameEn = "Year2026"
                        },
                        new
                        {
                            Id = 30,
                            Code = 2027,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3484),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2027",
                            NameEn = "Year2027"
                        },
                        new
                        {
                            Id = 31,
                            Code = 2028,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3487),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2028",
                            NameEn = "Year2028"
                        },
                        new
                        {
                            Id = 32,
                            Code = 2029,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3490),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2029",
                            NameEn = "Year2029"
                        },
                        new
                        {
                            Id = 33,
                            Code = 2030,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3492),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2030",
                            NameEn = "Year2030"
                        },
                        new
                        {
                            Id = 34,
                            Code = 2031,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 767, DateTimeKind.Local).AddTicks(3495),
                            Description = "",
                            IsActive = true,
                            IsDeleted = false,
                            LookupCategoryId = 600,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "Year2031",
                            NameEn = "Year2031"
                        });
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.LookupCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyOn");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("LookupCategory");

                    b.HasData(
                        new
                        {
                            CategoryId = 100,
                            Code = 1,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 762, DateTimeKind.Local).AddTicks(7238),
                            Description = "Training Type That TPS Provided",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "نوع التدريب",
                            NameEn = "Training Type"
                        },
                        new
                        {
                            CategoryId = 200,
                            Code = 2,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 764, DateTimeKind.Local).AddTicks(6641),
                            Description = "Training Topics That TPS Provided",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "موضوعات التدريب",
                            NameEn = "Training Topics"
                        },
                        new
                        {
                            CategoryId = 300,
                            Code = 3,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 764, DateTimeKind.Local).AddTicks(6683),
                            Description = "Training Status",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "حالة التدريب",
                            NameEn = "Training Status"
                        },
                        new
                        {
                            CategoryId = 400,
                            Code = 4,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 764, DateTimeKind.Local).AddTicks(6688),
                            Description = "Training Result",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "نتيجة التدريب",
                            NameEn = "Training Result"
                        },
                        new
                        {
                            CategoryId = 500,
                            Code = 5,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 764, DateTimeKind.Local).AddTicks(6691),
                            Description = "Trainer Name",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "أسم المدرب",
                            NameEn = "Trainer Name"
                        },
                        new
                        {
                            CategoryId = 600,
                            Code = 6,
                            CreatedBy = "Malek Hamdan",
                            CreatedOn = new DateTime(2023, 9, 11, 14, 47, 20, 764, DateTimeKind.Local).AddTicks(6694),
                            Description = "Training Year That TPS Provided",
                            IsActive = true,
                            IsDeleted = false,
                            ModifyOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameAr = "السنة",
                            NameEn = "Year"
                        });
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<double>("EvaluationScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FinalPresentationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyOn");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int?>("ResultLookupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusLookupId")
                        .HasColumnType("int");

                    b.Property<string>("TraineeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainerLookupId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerName")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTopic")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingTopicLookupId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingType")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingTypeLookupId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("ResultLookupId");

                    b.HasIndex("StatusLookupId");

                    b.HasIndex("TrainerLookupId");

                    b.HasIndex("TrainingTopicLookupId");

                    b.HasIndex("TrainingTypeLookupId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrainingManagment.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrainingManagment.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingManagment.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrainingManagment.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.Lookup", b =>
                {
                    b.HasOne("TrainingManagment.Domain.Models.LookupCategory", "LookupCategory")
                        .WithMany("Lookups")
                        .HasForeignKey("LookupCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupCategory");
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.Session", b =>
                {
                    b.HasOne("TrainingManagment.Domain.Models.Lookup", "ResultLookup")
                        .WithMany()
                        .HasForeignKey("ResultLookupId");

                    b.HasOne("TrainingManagment.Domain.Models.Lookup", "StatusLookup")
                        .WithMany()
                        .HasForeignKey("StatusLookupId");

                    b.HasOne("TrainingManagment.Domain.Models.Lookup", "TrainerLookup")
                        .WithMany()
                        .HasForeignKey("TrainerLookupId");

                    b.HasOne("TrainingManagment.Domain.Models.Lookup", "TrainingTopicLookup")
                        .WithMany()
                        .HasForeignKey("TrainingTopicLookupId");

                    b.HasOne("TrainingManagment.Domain.Models.Lookup", "TrainingTypeLookup")
                        .WithMany()
                        .HasForeignKey("TrainingTypeLookupId");

                    b.Navigation("ResultLookup");

                    b.Navigation("StatusLookup");

                    b.Navigation("TrainerLookup");

                    b.Navigation("TrainingTopicLookup");

                    b.Navigation("TrainingTypeLookup");
                });

            modelBuilder.Entity("TrainingManagment.Domain.Models.LookupCategory", b =>
                {
                    b.Navigation("Lookups");
                });
#pragma warning restore 612, 618
        }
    }
}
